### ISSUE TITLE
Compatibility with Microsoft Bot Framework

### ISSUE THREAD

**Issue by medicareamaze** [plone/create-volto-app#14]
Hi, I am trying to include Microsoft Bot Framework React Component to a Volto site and it throws errors. Can you help?

steps to reproduce.

1. Added a Full View as pet the documentation  https://training.plone.org/5/volto/custom-views.html#full-view

This is working correctly and I see the full vIew

2. I added the Microsoft Bot Framework react component  using command
 
<pre>yarn add  botframework-webchat
</pre>

3.  I added the import statement to the full view Component

import ReactWebChat from 'botframework-webchat';

4. I get the following error:

/home/srangaiah/medicareamaze/node_modules/botframework-webchat-component/node_modules/react-film/src/index.js:22
if (document && document.head) {
^
ReferenceError: document is not defined
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat-component/node_modules/react-film/src/index.js:22:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat-component/src/SendBox/SuggestedActions.js:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat-component/src/BasicSendBox.js:10:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat-component/src/BasicWebChat.js:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat-component/src/index.tsx:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat/src/index-minimal.ts:6:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/node_modules/botframework-webchat/src/index.ts:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.botframework-webchat (/home/srangaiah/medicareamaze/external "botframework-webchat":1:1)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/components/FullView/FullView.jsx (/home/srangaiah/medicareamaze/build/server.js:39663:78)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/components/index.js (/home/srangaiah/medicareamaze/build/webpack:/src/components/index.js:1:1)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/config.js (/home/srangaiah/medicareamaze/build/server.js:39877:69)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/components/theme/Anontools/Anontools.jsx (/home/srangaiah/medicareamaze/build/server.js:26836:70)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/components/index.js (/home/srangaiah/medicareamaze/build/webpack:/node_modules/@plone/volto/src/components/index.js:1:1)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/routes.js (/home/srangaiah/medicareamaze/build/server.js:39971:81)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/server.jsx (/home/srangaiah/medicareamaze/build/server.js:39238:70)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@plone/volto/src/start-server.js (/home/srangaiah/medicareamaze/build/webpack:/node_modules/@plone/volto/src/start-server.js:1:1)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Module../src/index.js (/home/srangaiah/medicareamaze/build/webpack:/src/index.js:1:1)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at fn (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:59:1)
    at Object.0 (/home/srangaiah/medicareamaze/build/server.js:40006:18)
    at __webpack_require__ (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:685:1)
    at module.exports../build/assets.json.module.exports.client.js (/home/srangaiah/medicareamaze/build/webpack:/webpack/bootstrap:752:1)
    at Object.<anonymous> (/home/srangaiah/medicareamaze/build/server.js:757:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by tisto** [comment]
Have you tried to add that package to a standard create-react-app package? This problem seems to unrelated to Volto at first sight.
